# Generated by Django 2.0.4 on 2018-04-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='added_by_admin',
            field=models.IntegerField(default=''),
        ),
    ]
