# Generated by Django 2.0.4 on 2018-04-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0002_user_added_by_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='added_by_admin',
            field=models.IntegerField(default=10),
        ),
    ]
