# Generated by Django 2.0.4 on 2018-04-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0002_auto_20180427_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_message',
            field=models.TextField(),
        ),
    ]
