# Generated by Django 2.0.4 on 2018-04-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0003_auto_20180427_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='added_by_admin',
            field=models.IntegerField(),
        ),
    ]
